### ISSUE TITLE
Toggling thumbnails breaks component

### ISSUE THREAD

**Issue by emiliemarchand** [banthagroup/fslightbox-vue#18]
Hello,
In the pro vue version, I get this error when toggling the thumbnails a couple of times:

> DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

This make the lightbox unusable (we can't close it or change picture etc.)

**Steps to reproduce:**
The bug can be reproduced in the [demo page of fslightbox](https://fslightbox.com/vue).

1. On the pro demo, click on one of the picture to open the lightbox
2. Click on the Thumbnails icon in the tool nav.
3. Click again the icon to hide the thumbs.
4. Click again to show the thumbs. The error should pop in the js console.

**Comment by piotrzdziarski** [comment]
Hi, it was fixed in 1.0.1 version.
