### ISSUE TITLE
Canť swipe on mobile device

### ISSUE THREAD

**Issue by DavidCejka** [banthagroup/fslightbox-vue#77]
Hello, I canť swipe between slides on mobile device. I can swipe only by mouse and by arrows. Anyone has same issue?
Is it working only in Pro version?

I'm using:
"dependencies": {
    "bootstrap": "^5.2.3",
    "core-js": "^3.8.3",
    "fslightbox-vue": "^2.0.1",
    "swiper": "^8.4.5",
    "vue": "^3.2.13",
    "vue-i18n": "^9.2.2",
    "vue-router": "^4.0.3"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-router": "~5.0.0",
    "@vue/cli-service": "~5.0.0"
  }

**Comment by belfortf** [comment]
I'm having the same issue, but only with Android phones, on iPhone it works well. @piotrzdziarski any info on that ?

**Comment by enforbAlzi** [comment]
Fix it please...

**Comment by piotrzdziarski** [comment]
Fixed in 2.1.3.
